import { m } from "../../paraglide/messages";
import type { StatChart } from "../types/charts";
import {
  getPreviousYear,
  getPreviousYearMonth,
  getYearMonthOffset,
  getYearOffset,
} from "../utils/common";

export const STAT_CHARTS: StatChart[] = [
  {
    title: m.net_income(),
    category: "INCOME",
    chartType: "ROLLING_AVERAGE",
    metric: "NET_INCOME",
    interval: "MONTHLY",
    startYearMonth: getYearMonthOffset(getPreviousYearMonth(), 11),
    endYearMonth: getPreviousYearMonth(),
  },
  {
    title: m.gross_salary_vs_previous_year(),
    category: "INCOME",
    chartType: "ROLLING_PERFORMANCE",
    metric: "GROSS_BASE_SALARY",
    interval: "MONTHLY",
    startYearMonth: getYearMonthOffset(getPreviousYearMonth(), 5),
    endYearMonth: getPreviousYearMonth(),
  },
  {
    title: m.gross_income(),
    category: "INCOME",
    chartType: "FIVE_YEAR_TREND",
    metric: "GROSS_INCOME",
    interval: "YEARLY",
    startYear: getYearOffset(getPreviousYear(), 4),
    endYear: getPreviousYear(),
  },
  {
    title: m.net_income(),
    category: "INCOME",
    chartType: "FIVE_YEAR_TREND",
    metric: "NET_INCOME",
    interval: "YEARLY",
    startYear: getYearOffset(getPreviousYear(), 4),
    endYear: getPreviousYear(),
  },
  {
    title: m.cumulative_gross_income(),
    category: "INCOME",
    chartType: "ALL_TIME_TOTAL",
    metric: "GROSS_INCOME",
    interval: "YEARLY",
  },
  {
    title: m.taxes(),
    category: "DEDUCTIONS",
    chartType: "ROLLING_AVERAGE",
    metric: "TAXES",
    interval: "MONTHLY",
    startYearMonth: getYearMonthOffset(getPreviousYearMonth(), 11),
    endYearMonth: getPreviousYearMonth(),
  },
  {
    title: m.income_tax(),
    category: "DEDUCTIONS",
    chartType: "FIVE_YEAR_TREND",
    metric: "INCOME_TAX",
    interval: "YEARLY",
    startYear: getYearOffset(getPreviousYear(), 4),
    endYear: getPreviousYear(),
  },
  {
    title: m.social_deductions(),
    category: "DEDUCTIONS",
    chartType: "ROLLING_AVERAGE",
    metric: "INSURANCE_DEDUCTIONS",
    interval: "MONTHLY",
    startYearMonth: getYearMonthOffset(getPreviousYearMonth(), 11),
    endYearMonth: getPreviousYearMonth(),
  },
  {
    title: m.health_insurance_vs_previous_year(),
    category: "DEDUCTIONS",
    chartType: "ROLLING_PERFORMANCE",
    metric: "HEALTH_INSURANCE",
    interval: "MONTHLY",
    startYearMonth: getYearMonthOffset(getPreviousYearMonth(), 5),
    endYearMonth: getPreviousYearMonth(),
  },
  {
    title: m.health_insurance(),
    category: "DEDUCTIONS",
    chartType: "FIVE_YEAR_TREND",
    metric: "HEALTH_INSURANCE",
    interval: "YEARLY",
    startYear: getYearOffset(getPreviousYear(), 4),
    endYear: getPreviousYear(),
  },
  {
    title: m.pension_insurance_vs_previous_year(),
    category: "DEDUCTIONS",
    chartType: "ROLLING_PERFORMANCE",
    metric: "PENSION_INSURANCE",
    interval: "MONTHLY",
    startYearMonth: getYearMonthOffset(getPreviousYearMonth(), 5),
    endYearMonth: getPreviousYearMonth(),
  },
  {
    title: m.pension_insurance(),
    category: "DEDUCTIONS",
    chartType: "FIVE_YEAR_TREND",
    metric: "PENSION_INSURANCE",
    interval: "YEARLY",
    startYear: getYearOffset(getPreviousYear(), 4),
    endYear: getPreviousYear(),
  },
  {
    title: m.cumulative_pension_insurance(),
    category: "DEDUCTIONS",
    chartType: "ALL_TIME_TOTAL",
    metric: "PENSION_INSURANCE",
    interval: "YEARLY",
  },
  {
    title: m.gross_bonus(),
    category: "BONUS",
    chartType: "FIVE_YEAR_TREND",
    metric: "GROSS_BONUS_SALARY",
    interval: "YEARLY",
    startYear: getYearOffset(getPreviousYear(), 4),
    endYear: getPreviousYear(),
  },
  {
    title: m.net_bonus(),
    category: "BONUS",
    chartType: "FIVE_YEAR_TREND",
    metric: "NET_BONUS_SALARY",
    interval: "YEARLY",
    startYear: getYearOffset(getPreviousYear(), 4),
    endYear: getPreviousYear(),
  },
];
